### ISSUE TITLE
Random movement

### ISSUE THREAD

**Issue by VladPog** [markknol/flash-jsfl-tools#2]
Hello, Mark! Would you be so kind as to add to "flash-jsfl-tools" a script for random movement instances?
I will very much obliged to you!

**Comment by markknol** [comment]
What do you mean with random movement instances? Move objects with certain offset?

Best thing to look at is this script: Copy/paste it 
https://github.com/markknol/flash-jsfl-tools/blob/master/commands/%5Bmm%5D%20Random%20rotation.jsfl

Copy/paste it and replace this line:
```js
selectedItem.rotation = rotations[Math.floor(Math.random() * rotations.length)];
```
with something like this:
```js
selectedItem.x += -10 + Math.random() * 20;
selectedItem.y += -10 + Math.random() * 20;
```

**Comment by VladPog** [comment]
It works
Thanks a lot!

**Comment by markknol** [comment]
🎉 nice! if you need any other script let me know.
